### ISSUE TITLE
Create .gitignore file

### ISSUE THREAD

**Issue by ramuta** [MarkusHiersche89/SmartNinja_Git#1]
Hi Markus,

I suggest you create a `.gitignore` file in which you'll add all the files and folders that shouldn't be added to Git (and uploaded to GitHub). These files are usually IDE configuration files, databases, binaries etc.

I suggest that you copy the content of this file into your own `.gitignore` file: https://github.com/github/gitignore/blob/master/Python.gitignore

In addition, you can add the following file/folder names in `.gitignore`:

```
bin
.idea
*.cfg
```

---

Btw, your `git_pull.sh` script has a typo:

```
git pull origin maste
```

"r" is missing at the end ;)

**Comment by MarkusHiersche89** [comment]
the "r" at the script was edited...
thanks a lot.

ps.: i need all files (at the moment) ,-)
